with-expecter: true
dir: "{{.InterfaceDir}}/mocks"
filename: "mock_{{.InterfaceNameSnake}}.go"
outpkg: "mocks"
mockname: "{{.InterfaceName}}"
resolve-type-alias: False
issue-845-fix: True

packages:
    github.com/gomeal/meal-api/internal/clients:
        config:
            include-regex: "|.*Client$|.*Config$"
    github.com/gomeal/meal-api/internal/repositories:
        config:
            include-regex: ".*Repository$"
